"""Add category and ingredients to Dish

Revision ID: cfafd56b0800
Revises: 
Create Date: 2025-04-11 15:59:45.088495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfafd56b0800'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Добавляем столбец category как NULL
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))  # Сначала добавляем как NULL
        batch_op.add_column(sa.Column('ingredients', sa.String(length=500), nullable=True))

    # Устанавливаем значение по умолчанию для существующих записей
    connection = op.get_bind()
    connection.execute("UPDATE dish SET category = 'default_category' WHERE category IS NULL")

    # Теперь можно изменить столбец на NOT NULL
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.alter_column('category', nullable=False)  # Изменяем на NOT NULL

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_column('ingredients')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
